### PR TITLE
Remove server name nginx config

### PR DESCRIPTION
**Pull request by hdhruna**
Remove server_name option to use an empty name

### CODE REVIEW

**Review by markjacksonfishing — CHANGES_REQUESTED** [review]
You will need to sign the easycla for this

**Comment by sbtaylor15** [comment]
> You will need to sign the easycla for this

The should be covered by the company CLA.  Need to check to see if the GitHub handle is associated with the company correctly.

**Comment by hdhruna** [comment]
Yes @sbtaylor15 I am working with my Priceline Legal team on this.

**Comment by sbtaylor15** [comment]
> Yes @sbtaylor15 I am working with my Priceline Legal team on this.

I believe @Ujwal90210 was setting you up under Interbase

**Comment by sbtaylor15** [comment]
Closing due to CLA issue.

**Pull request closed without merging**
